name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - feature/frontend
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - feature/frontend
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
      - name: Install dependencies
        run: |
          cd HockeyRinkWeb
          npm install
      - name: Build application
        run: |
          cd HockeyRinkWeb
          npm run build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_RIVER_0C3237510 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: './HockeyRinkWeb/dist/HockeyRinkWeb/browser'
          api_location: ''
          output_location: ''
          skip_app_build: true
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_RIVER_0C3237510 }}
          action: 'close'
  build_and_deploy_api_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy API Job
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore HockeyRinkAPI/HockeyRinkAPI.csproj
      - name: Build
        run: dotnet build HockeyRinkAPI/HockeyRinkAPI.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish HockeyRinkAPI/HockeyRinkAPI.csproj --configuration Release --output ./publish
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hockey-rink-api-bbhch3gwgzedc9e3'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: ./publish
